### ISSUE TITLE
Scheme validation is not getting picked up by astrum-cli

### ISSUE THREAD

**Issue by ghost** [apiwizlabs/astrum#4]
Check when there’s no scheme tag is present in the input swagger file, the linting rule to validate the value of scheme tag is processed

**Comment by chinmayee-itorix** [comment]
OUTPUT:
![image](https://user-images.githubusercontent.com/103993332/163961050-d5fe8bba-ff6c-4bb1-b327-2e939e7652a8.png)
INPUT RULE CONFIG: 
![image](https://user-images.githubusercontent.com/103993332/163961152-7869b1f3-8857-4a44-b9ea-99aba96bb558.png)
INPUT OAS FILE:
http://rackerlabs.github.io/wadl2swagger/openstack/swagger/dbaas.json

**Comment by AkashItorix** [comment]
The reason for this issue is while generating the linting report in SwaggerLinterHelper class in the core module only the "present" assertion rule is checked. Therefore the issue is solved by checking the  other necessary assertion rules. The attached file is the test cases for the changes implemente
[Book1.xlsx](https://github.com/apiwizlabs/astrum/files/8720496/Book1.xlsx)
d
